window:
  padding:
    x: 8
    y: 8

  # TODO: This isn't working 
  opacity: 0.8

font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic

  size: 16.0

  # Add a bit more spacing around text characters because the default feels
  # cramped
  offset:
    x: 1
    y: 1
