#!/usr/bin/env bash

function yell () { >&2 echo "$*";  }
function die () { yell "$*"; exit 1; }
function try () { "$@" || die "Command failed: $*"; }

SCRIPT_PATH="$( realpath "$0" )"
SCRIPT_DIR="$( dirname "$SCRIPT_PATH" )"

CONTEXT_FILES=(
    #"./initial_setup.md"
    #"./mypy.ini"
    #"./provision/manjaro.sh"
    #"./provision/ubuntu.sh"
##    "./provision/ubuntu_22.04.sh"
##    "./bootstrap.sh"
##    "./nix/home/features/wsl.nix"
##    "./nix/home/features/desktop.nix"
##    "./nix/home/features/dotfiles-links.nix"
##    "./nix/home/features/core.nix"
##    "./nix/home/features/gaming.nix"
##    "./nix/home/hosts/work-wsl.nix"
##    "./nix/home/hosts/work-desktop.nix"
##    "./nix/home/hosts/personal-desktop.nix"
##    "./nix/home/hosts/work-server.nix"
##    "./nix/home/hosts/personal-server.nix"
##    "./nix/home/hosts/personal-wsl.nix"
##    "./nix/flake.nix"
    #"./nix/flake.lock"
    #"./.gitignore"
    #"./.isort.cfg"
    #"./LICENSE"
    #"./Makefile"
    #"./templates/nvimp.template.py"
    #"./links.json"
    #"./cli/dot.py"
    #"./cli/commands/git_sync.py"
    #"./cli/commands/provision.py"
    #"./cli/commands/link.py"
    #"./cli/commands/tidy.py"
    #"./cli/commands/fd/__init__.py"
    #"./cli/commands/list.py"
    #"./cli/commands/lint.py"
    #"./cli/commands/clean.py"
    #"./cli/commands/status.py"
    #"./cli/commands/__init__.py"
    #"./cli/lib/provision/provisioner_i3.py"
    #"./cli/lib/provision/provisioner_kitty.py"
    #"./cli/lib/provision/provisioner_nodejs.py"
    #"./cli/lib/provision/provisioner_pip.py"
    #"./cli/lib/provision/provisioner_apt.py"
    #"./cli/lib/provision/system_provisioner.py"
    #"./cli/lib/provision/tag.py"
    #"./cli/lib/provision/provisioner_ripgrep.py"
    #"./cli/lib/provision/provisioner_dot.py"
    #"./cli/lib/provision/symlink.py"
    #"./cli/lib/provision/provisioner_docker.py"
    #"./cli/lib/provision/provisioner_neovim.py"
    #"./cli/lib/provision/provisioner.py"
    #"./cli/lib/provision/provisioner_win32yank.py"
    #"./cli/lib/provision/provisioner_flavours.py"
    #"./cli/lib/provision/provisioner_treesitter.py"
    #"./cli/lib/provision/__init__.py"
    #"./cli/lib/shell/install_flavours.sh"
    #"./cli/lib/common/apt.py"
    #"./cli/lib/common/archive.py"
    #"./cli/lib/common/links.py"
    #"./cli/lib/common/user.py"
    #"./cli/lib/common/shell.py"
    #"./cli/lib/common/semver.py"
    #"./cli/lib/common/dir.py"
    #"./cli/lib/common/group.py"
    #"./cli/lib/common/log.py"
    #"./cli/lib/common/util.py"
    #"./cli/lib/common/linter.py"
    #"./cli/lib/common/typing.py"
    #"./cli/lib/common/alternatives.py"
    #"./cli/lib/common/git.py"
    #"./cli/lib/common/pip.py"
    #"./cli/lib/common/version_cache.py"
    #"./cli/lib/common/github.py"
    #"./cli/lib/common/file_walker.py"
    #"./cli/lib/common/os.py"
    #"./cli/lib/common/distro_info.py"
    #"./cli/lib/common/__init__.py"
    #"./cli/lib/__init__.py"
    #"./cli/README.md"
    #"./dot.sh"
    #"./bin/nb"
    #"./bin/snipping-tool"
    #"./bin/calculator"
    #"./bin/startup.sh"
    #"./bin/bcompare_svnrev"
    #"./bin/git_pending_changes.py"
    #"./bin/fzf_cached_wsl"
    #"./bin/i3-util.sh"
    #"./bin/i3exit"
    #"./bin/fssh"
    #"./bin/colortest.py"
    #"./bin/set_mouse_sensitivty.sh"
    #"./bin/set_default_browser.sh"
    #"./bin/lock"
    #"./bin/docker_clean.sh"
    #"./bin/cleanup_logs.sh"
    #"./bin/set-theme"
    #"./bin/clone.py"
    #"./bin/dgit.sh"
    #"./bin/swayexit"
    #"./bin/compare.sh"
    #"./bin/i3-get-window-criteria.sh"
    #"./bin/fuzzy-fm"
    #"./bin/bcompare_svn"
    #"./bin/get_ip.py"
    #"./bin/run_compositor.sh"
    #"./bin/textpack"
    #"./README.md"
    #"./todo.md"
    #"./flatten.sh"
    #"./config/alacritty/linux.yml"
    #"./config/alacritty/windows.yml"
    #"./config/alacritty/base16.yml"
    #"./config/sway-user.desktop"
    #"./config/picom.conf"
    #"./config/vsvimrc"
    #"./config/gvimrc"
    #"./config/gitconfig"
    #"./config/bashrc"
    #"./config/rofi/config.rasi"
    #"./config/rofi/base16.rasi"
    #"./config/env"
    #"./config/i3"
    #"./config/swaysession"
    #"./config/dunstrc"
    #"./config/pulse/daemon.conf"
    #"./config/py3status.conf"
    #"./config/xsession"
    "./config/nvim/init.lua"
    #"./config/nvim/UltiSnips/sh.snippets"
    #"./config/nvim/UltiSnips/tex.snippets"
    #"./config/nvim/UltiSnips/cpp.snippets"
    #"./config/nvim/UltiSnips/markdown.snippets"
    #"./config/nvim/UltiSnips/python.snippets"
    "./config/nvim/lua/dot/log.lua"
    "./config/nvim/lua/dot/plugins.lua"
    "./config/nvim/lua/dot/theme.lua"
    "./config/nvim/lua/dot/map.lua"
    "./config/nvim/lua/dot/settings.lua"
    "./config/nvim/lua/dot/util.lua"
    "./config/nvim/lua/dot/lsp_clangd.lua"
    "./config/nvim/lua/dot/treesitter.lua"
    "./config/nvim/lua/dot/wsl.lua"
    "./config/nvim/lua/dot/globals.lua"
    "./config/nvim/lua/dot/vim_plug.lua"
    "./config/nvim/lua/dot/notifications.lua"
    "./config/nvim/lua/dot/mappings.lua"
    "./config/nvim/lua/dot/lsp_jedi.lua"
    "./config/nvim/lua/dot/lsp_gopls.lua"
    #"./config/nvim/syntax/cwiki.vim"
    #"./config/xsession.desktop"
    #"./config/inputrc"
    #"./config/ncmpcpp/bindings"
    #"./config/ncmpcpp/config"
    #"./config/rangerrc"
    #"./config/wezterm.lua"
    #"./config/bash_profile"
    #"./config/mpd"
    #"./config/flavours/templates/custom/templates/xresources.mustache"
    #"./config/flavours/templates/custom/templates/wezterm.mustache"
    #"./config/flavours/templates/custom/templates/kitty-256.mustache"
    #"./config/flavours/templates/custom/templates/tmux.mustache"
    #"./config/flavours/templates/custom/templates/i3.mustache"
    #"./config/flavours/templates/custom/templates/dunstrc.mustache"
    #"./config/flavours/templates/custom/templates/vimrc.mustache"
    #"./config/flavours/templates/custom/templates/py3status.mustache"
    #"./config/flavours/templates/custom/templates/nvim.mustache"
    #"./config/flavours/templates/custom/templates/bashrc.mustache"
    #"./config/flavours/templates/custom/templates/rofi.mustache"
    #"./config/flavours/templates/custom/templates/alacritty.mustache"
    #"./config/flavours/schemes/custom/solarized-dark.yaml"
    #"./config/flavours/schemes/custom/dracula.yml"
    #"./config/flavours/schemes/custom/outrun-dark.yaml"
    #"./config/flavours/config.toml"
    #"./config/bash/aliases.sh"
    #"./config/bash/base16.sh"
    #"./config/bash/functions.sh"
    #"./config/bash/dprof.sh"
    #"./config/bash/core.sh"
    #"./config/profile"
    #"./config/xinitrc"
    #"./config/Xresources"
    #"./config/tmux.conf"
    #"./config/chrome/home.html"
    #"./config/chrome/pico.min.css"
    #"./config/chrome/README.md"
    #"./config/vimrc"
    #"./config/sway"
    #"./config/alacritty.yml"
    #"./config/kitty.conf"
    #"./temp.md"
)

function output_context_file() {
    local context_file="$1"

    echo -e "\nFile \`${context_file}\`:"
    echo -e "\`\`\`"
    cat "${context_file}"
    echo -e "\`\`\`"
}

echo "Context Files:"

for CONTEXT_FILE in "${CONTEXT_FILES[@]}"; do
    output_context_file "$CONTEXT_FILE"
done
