#!/usr/bin/env bash

DOTFILES="$HOME/.dotfiles"

print_usage() {
  echo "Usage: ./setup [OPTIONS]"
  echo -en '\n'

  echo "Options:"

  echo "  -c            Clean; remove symbolic links"
  echo "  -h            Help; displays usage dialog"
  echo "  -l            Link; create symbolic links"
  echo "  -r            Remote; indicates the script is running on a remote machine so GUI applications such as urxvt are not installed or configured"
  echo -en '\n'
}

print_section_header() {
  echo -en '\n'
  echo "$1"
  echo "==============================================================="
}

clean() {
  print_section_header "Clean"

  if [[ $remote = true ]]; then
    echo "Cleaning remote configuration dotfiles..."
  else
    echo "Cleaning local configuration dotfiles..."
  fi

  source "$DOTFILES/scripts/clean.sh" "$remote"
}

link() {
  print_section_header "Link"

  if [[ $remote = true ]]; then
    echo "Linking remote configuration dotfiles..."
  else
    echo "Linking local configuration dotfiles..."
  fi

  source "$DOTFILES/scripts/link.sh" "$remote"
}

clean=false
distro=""
link=false
remote=false

while getopts ":chlr" flag
do
  case "$flag" in
    "c")
      clean=true
      ;;
    "h")
      print_usage
      exit 0
      ;;
    "l")
      link=true
      ;;
    "r")
      remote=true
      ;;
    *)
      print_usage
      exit 1
      ;;
  esac
done

if [[ $clean = true ]]; then
  clean
fi

if [[ $link = true ]]; then
  link
fi

