# This is based on the upstream base16 dracula scheme:
# https://github.com/dracula/base16-dracula-scheme
#
# That scheme didn't actually use the real dracula palette and the green and
# yellow are in the wrong place so I've addressed those two problems. The color
# palette provided on https://draculatheme.com only specifies 11 colors so the
# remaining 5 I left the same as base16-dracula-scheme.
scheme: "Dracula"
author: "Paul Ewing (http://github.com/pcewing)"
base00: "282A36" # Previousl: "282936"
base01: "3A3C4E" # Unchanged
base02: "44475A" # Previously: "4d4f68"
base03: "6272A4" # Previously: "626483"
base04: "62D6E8" # Unchanged
base05: "F8F8F2" # Previously: "e9e9f4"
base06: "F1F2F8" # Unchanged
base07: "F7F7FB" # Unchanged
base08: "FF5555" # Previously: "ea51b2"
base09: "FFB86C" # Previously: "B45BCF"
base0A: "F1FA8C" # Previously: "00f769"
base0B: "50FA7B" # Previously: "ebff87"
base0C: "8BE9FD" # Previously: "a1efe4"
base0D: "BD93F9" # Previously: "62d6e8"
base0E: "FF79C6" # Previously: "b45bcf"
base0F: "00F769" # Unchanged
