# The windows.yml and linux.yml imports below provide a mechanism for loading
# different configuration on those operating systems. All imports are optional.
# Files that don't exist are ignored. To see what config files are being
# loaded, run alacritty with highest verbosity:
#
#     alacritty -vvv >~/alacritty.log
#
# And look for the following log lines:
#
# - Config import not found
# - Configuration files loaded from
#
# The paths specified are relative to $HOME regardless of what working
# directory is specified when launching alacritty.
#
# So, the below should gracefully support different configs per OS as long as
# only the desired config files are linked to ~/.config/alacritty:
import:
  - ~/.config/alacritty/windows.yml
  - ~/.config/alacritty/linux.yml
  - ~/.config/alacritty/base16.yml
