shell:
  program: C:\Program Files\Git\bin\bash.exe
  args:
  - --login

# On Windows this may launch in the C:\WINDOWS\system32 directory. The below
# doesn't accept variable names so to make sure it launches into home across
# different machines where username may vary, it's better to just modify the
# shortcut.
#
# Navigate to the shortcut from the Start Menu and set the "Start in" field to:
# C:\Users\USERNAME
#working_directory: C:\Users\foo

font:
  normal:
    family: Ubuntu Mono derivative Powerline
    #family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono derivative Powerline
      #family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono derivative Powerline
      #family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono derivative Powerline
      #family: Ubuntu Mono
    style: Bold Italic

  size: 16

  # Ideally the default offset would look nice but for whatever reason on
  # Windows it feels cramped so add a bit more spacing around text
  offset:
    x: 1
    y: 1

# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Template
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
    bar:
      background: '#282a36'
      foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'
