#!/usr/bin/env bash

[[ -f "$HOME/.env" ]] && . "$HOME/.env"

. "$DOTFILES/config/bash/core.sh"

export EDITOR='nvim'

# Load custom utilities
. "$DOTFILES/config/bash/aliases.sh"
. "$DOTFILES/config/bash/functions.sh"

src_if_exists() {
   [[ -f "$1" ]] && . "$1"
}

declare -a sources=(
    "$HOME/.localrc"

    # No need to filter this out on non-WSL hosts because Nix won't link it
    "$HOME/.wslrc"
)

for i in "${sources[@]}"; do
    src_if_exists  "$i"
done

# Source fzf shell integrations if we have them
if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
  source "$(fzf-share)/completion.bash"
fi

# Prompt
black="\[\033[30m\]"
red="\[\033[31m\]"
green="\[\033[32m\]"
yellow="\[\033[33m\]"
blue="\[\033[34m\]"
purple="\[\033[35m\]"
cyan="\[\033[36m\]"
white="\[\033[37m\]"
none="\[\033[00m\]"

PS1="${white}[${green}\u${white}@${blue}\H${white}:${yellow}\w${white}] "

# Bash auto-completion for dotfiles CLI
export DOT_BASH_COMPLETION="1"
if [ -f "$HOME/.config/bash/completions/dot" ]; then
  source "$HOME/.config/bash/completions/dot"
fi

# Node.js configuration
if [ -d "$HOME/.nvm" ]; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
fi

# Golang configuration
if _is_installed "go"; then
    # Set GOPATH
    export GOPATH="$HOME/go"
fi

# Rust configuration
if _is_installed "rust"; then
    [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
fi

# Initialize base16 color system
. "$DOTFILES/config/bash/base16.sh"
        
# TODO: Move this into base16.sh. Will need to adjust our flavours configs
# Start flavours - bashrc

# Base16 Outrun Dark

if command -v "base16_outrun-dark" >/dev/null 2>&1; then
    eval "base16_outrun-dark"
fi
# End flavours - bashrc

# TODO: I think this was automatically appended and I didn't notice and
# accidentally committed it. We should put this somewhere that makes more
# sense.
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# VS Code Shell integration, see:
# https://code.visualstudio.com/docs/terminal/shell-integration
# TODO: For this and teh block below, maybe let's just move all VS Code stuff
# to a config/bash/vscode.sh file and then do a single:
#     [[ "$TERM_PROGRAM" == "vscode" ]] && source vscode.sh
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path bash)"

# When running in VS Code, automatically activate a Python virtual environment
# since agents seem to struggle to consistently do this
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
    if [ -d "$HOME/dot/.venv" ]; then
        . "$HOME/dot/.venv/Scripts/activate"
    else
        python -m venv "$HOME/dot/.venv"
        . "$HOME/dot/.venv/Scripts/activate"
        python -m pip install -r "$HOME/dot/requirements.txt"
    fi
fi
