#!/usr/bin/env bash

[[ -f "$HOME/.env" ]] && . "$HOME/.env"

. "$DOTFILES/config/bash/core.sh"

export EDITOR='nvim'

# Load custom utilities
. "$DOTFILES/config/bash/aliases.sh"
. "$DOTFILES/config/bash/functions.sh"

src_if_exists() {
   [[ -f "$1" ]] && . "$1"
}

declare -a sources=(
    "$HOME/.fzf.bash"
    "$HOME/.localrc"
)

for i in "${sources[@]}"; do
    src_if_exists  "$i"
done

# Prompt
black="\[\033[30m\]"
red="\[\033[31m\]"
green="\[\033[32m\]"
yellow="\[\033[33m\]"
blue="\[\033[34m\]"
purple="\[\033[35m\]"
cyan="\[\033[36m\]"
white="\[\033[37m\]"
none="\[\033[00m\]"

PS1="${white}[${green}\u${white}@${blue}\H${white}:${yellow}\w${white}] "

# Node.js configuration
if [ -d "$HOME/.nvm" ]; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
fi

# Golang configuration
if _is_installed "go"; then
    # Set GOPATH
    export GOPATH="$HOME/go"
fi

# Rust configuration
if _is_installed "rust"; then
    [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
fi

# Bash auto-completion for dotfiles CLI
export DOT_BASH_COMPLETION="1"
source "$HOME/.bash_completion.d/dot.bash"

# Base16 color scheme
base16_shell_dir="$HOME/.config/base16-shell"
[ ! -d "$base16_shell_dir" ] && \
    git clone "https://github.com/chriskempson/base16-shell.git" \
        "$base16_shell_dir"

BASE16_SHELL_SET_BACKGROUND=true
if uname | grep -i 'linux' &>/dev/null; then
    BASE16_SHELL_SET_BACKGROUND=false
fi
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        source "$BASE16_SHELL/profile_helper.sh"
        
# Start flavours - bashrc

# Base16 Outrun Dark

eval "base16_outrun-dark"
# End flavours - bashrc
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
