set nocompatible

set number                        " Show line numbers
set backspace=indent,eol,start    " Make backspace behave as expected in insert mode
set history=1000                  " Increase :cmdline history
set showcmd                       " Show incomplete commands
set showmode                      " Show current mode
set gcr=a:blinkon0                " Disable cursor blink
set visualbell                    " No sounds
set autoread                      " Reload files changed outside vim
set autowrite                     " Write the file on :make
set nohidden                      " Hide buffer instead of closing it
set splitright                    " When splitting vertically, the new pane should be on the right
set splitbelow                    " When splitting horizontally, the new pane should be on the bottom
set ruler                         " Show the line & column number at cursor
set pastetoggle=<F2>              " See: http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
set clipboard=unnamed,unnamedplus " Use system clipboard if possible
set cursorline                    " Add a visual indicator to the line the cursor is on
set nojoinspaces                  " Don't insert an extra space after periods when joining lines

if !isdirectory('~/.vim/tmp')
    call mkdir($HOME . "/.vim/tmp", "p", 0775)
endif

set backupdir=~/.vim/tmp//,.
set directory=~/.vim/tmp//,.

if has('nvim')
    set laststatus=3              " Use global status line (Only supported in nvim 0.7+)
else
    set laststatus=2              " Always display the status line
endif

" Indentation
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

" Set the Leader key. I leave the leader key as '\' and remap ' ' to it
" instead of setting ' ' as the leader. This is so that showcmd is actually
" useful.
map <Space> <Leader>

" Install vim-plug automatically on Linux if it isn't already
if has('unix')
    if has('nvim')
        if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
            silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
        endif
    else
        if empty(glob('~/.vim/autoload/plug.vim'))
            silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
        endif
    endif
endif

filetype plugin on

" Load Plugins
call plug#begin('~/.config/nvim/plugged')

" Colorschemes
Plug 'chriskempson/base16-vim'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
"Plug 'elixir-lang/vim-elixir'
"Plug 'slashmili/alchemist.vim'
"Plug 'editorconfig/editorconfig-vim'
"Plug 'Valloric/YouCompleteMe'

Plug 'rodjek/vim-puppet'

Plug 'fatih/vim-go'
Plug 'OrangeT/vim-csharp'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-vinegar'
Plug 'nvie/vim-flake8'
Plug 'tikhomirov/vim-glsl'
Plug 'martinda/Jenkinsfile-vim-syntax'
Plug 'aklt/plantuml-syntax'
Plug 'elubow/cql-vim'
Plug 'tpope/vim-fugitive'
Plug 'honza/vim-snippets'
Plug 'igankevich/mesonic'
Plug 'rhysd/vim-clang-format'

if has('unix')
    Plug 'sirver/UltiSnips'
endif

if has('nvim')
    " New plugins to use neovim 0.5 features
    Plug 'neovim/nvim-lspconfig'
    " Sometimes the atuomatic :TSUpdate won't run successfully and then it
    " won't rerun. If cryptic treesitter errors show up after running
    " :PlugUpdate, try running :TSUpdate manually
    Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
    Plug 'nvim-lua/completion-nvim'
    Plug 'nvim-lua/popup.nvim'
    Plug 'nvim-lua/plenary.nvim'
    Plug 'glepnir/lspsaga.nvim'
    Plug 'hoob3rt/lualine.nvim'
    Plug 'nvim-telescope/telescope.nvim'
    Plug 'ixru/nvim-markdown'
endif

call plug#end()

" Don't use smart indent in markdown files
autocmd FileType markdown setlocal nosmartindent

let g:vim_markdown_frontmatter = 1

" Format the current C/C++ file with clang-format (Uses vim-clang-format plugin)
let g:clang_format#detect_style_file = 1
autocmd FileType c,cpp vnoremap <buffer><Leader>q :ClangFormat<CR>

" Format the current Python file with black
autocmd FileType python nnoremap <buffer><Leader>q :lua format_current_python_file()<CR>

" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsListSnippets="<c-tab>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

" FZF
nnoremap <Leader>o :Files<CR>
nnoremap <leader>t :Tags<cr>

" Telescope
nnoremap <leader>ff :Telescope find_files<cr>
nnoremap <leader>ft :Telescope tags<cr>
nnoremap <leader>fs :Telescope lsp_dynamic_workspace_symbols<cr>
"nnoremap <leader>fg :Telescope live_grep<cr>
"nnoremap <leader>fb :Telescope buffers<cr>
"nnoremap <leader>fh :Telescope help_tags<cr>

" LSP
nnoremap <leader>ls :LspStop<cr>

nnoremap <Leader>m :make<CR>

nnoremap <Leader>bn :bn<CR>
nnoremap <Leader>bp :bp<CR>
nnoremap <Leader>be :Ex<CR>
nnoremap <Leader>bf :n<Space>
nnoremap <Leader>bd :bd<CR>
nnoremap <leader>bl :ls<cr>:buffer<space>

nnoremap <Leader>cn :cn<CR>
nnoremap <Leader>cp :cp<CR>
nnoremap <Leader>co :copen<CR>
nnoremap <Leader>cc :cclose<CR>

nnoremap <leader>ssx :set syntax=
nnoremap <leader>ssg :set syntax=groovy<cr>

nnoremap <Leader>[ :!ctags -R<CR>

nnoremap <silent> <leader><Up> :resize +5<cr>
nnoremap <silent> <leader><Down> :resize -5<cr>
nnoremap <silent> <leader><Right> :vertical resize +5<cr>
nnoremap <silent> <leader><Left> :vertical resize -5<cr>

" Open current file in a second tab and make it the last tab
nnoremap <leader><tab> :tab split<CR>:tabm<CR>

nnoremap <A-F1> 1gt
nnoremap <A-F2> 2gt
nnoremap <A-F3> 3gt
nnoremap <A-F4> 4gt
nnoremap <A-F5> 5gt
nnoremap <A-F6> 6gt
nnoremap <A-F7> 7gt
nnoremap <A-F8> 8gt
nnoremap <A-F9> 9gt
nnoremap <A-F0> 10gt
nnoremap <leader>1 1gt
nnoremap <leader>2 2gt
nnoremap <leader>3 3gt
nnoremap <leader>4 4gt
nnoremap <leader>5 5gt
nnoremap <leader>6 6gt
nnoremap <leader>7 7gt
nnoremap <leader>8 8gt
nnoremap <leader>9 9gt
nnoremap <leader>0 10gt

" Save out buffers
nnoremap <silent> <leader>w :wa<cr>

" Clear search highlighting
nnoremap <silent> <leader><esc> :noh<cr>

" Print the current file path
nnoremap <silent> <leader>p :echo @%<cr>

" Copy file path and line number of current line to clipboard
nnoremap <silent> <leader>y :let @+ = join([expand('%'),  line(".")], ':')<cr>

" Start flavours - vimrc

" Base16 Outrun Dark

" Loads the scheme from:
" https://github.com/chriskempson/base16-vim

let base16colorspace=256
colorscheme base16-outrun-dark
" End flavours - vimrc

if has('win32')
    set background=dark
else
    " On Non-Windows operating systems, use the host window's background. This
    " allows for transparency if the terminal emulator has that configured.
    hi Normal guibg=NONE ctermbg=NONE
endif

if has('nvim')
    nnoremap <silent> <leader>x :e ~/.config/nvim/init.vim<cr>
else
    nnoremap <silent> <leader>x :e ~/.vimrc<cr>
endif

" Source lua files in Neovim
if has('nvim')
    luafile ~/dot/config/nvim/functions.lua
    luafile ~/dot/config/nvim/lsp_clangd.lua
    luafile ~/dot/config/nvim/lsp_gopls.lua
    luafile ~/dot/config/nvim/lsp_jedi.lua
    luafile ~/dot/config/nvim/treesitter.lua
endif
