#!/usr/bin/env bash

# Remove the background highlighting of folders in ls
LS_COLORS=$LS_COLORS:'ow=1;34:'
export LS_COLORS

if [ "$TERM_PROGRAM" = "WezTerm" ] && [ -f "$HOME/wezterm.sh" ]; then
    source "$HOME/wezterm.sh"
fi
