#!/bin/sh

# This script may be invoked when starting an X11 session via a display manager
# or otherwise. For more information, see:
# https://wiki.debian.org/Xsession
#
# To run shellcheck properly on this file:
# $ cd ~/dot/config
# $ shellcheck --shell=dash -x ./env ./xsession

# Add user-defined fonts (only if directory exists)
if [ -d "$HOME/.fonts" ]; then
  xset +fp "$HOME/.fonts"
  xset fp rehash
fi

# Disable bell
xset -b

# Enable zapping (C-A-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp

# Enforce correct locales from the beginning
unset LC_COLLATE
export LC_CTYPE=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=C
export LC_PAPER=en_US.UTF-8
export LC_NAME=en_US.UTF-8
export LC_ADDRESS=en_US.UTF-8
export LC_TELEPHONE=en_US.UTF-8
export LC_MEASUREMENT=en_US.UTF-8
export LC_IDENTIFICATION=en_US.UTF-8

# Use XToolkit in java applications
export AWT_TOOLKIT=XToolkit

# Set background color
xsetroot -solid "#333333"

# Set maximum core dump file size to unlimited
# Note that shellcheck will warn that `ulimit -c` is not supported in POSIX sh;
# however, dash is the standard implementation of sh on Linux and it does
# support this. See comments at the top of file for properly running shellcheck
# on this script.
ulimit -c unlimited

# Set up environment variables
# shellcheck source=./env
if [ -f "$HOME/dot/config/env" ]; then
  . "$HOME/dot/config/env"
  echo "Sourced env, Path = $PATH" >> "$HOME/xsession-debug.log"
else
  echo "ERROR: $HOME/dot/config/env not found" >> "$HOME/xsession-debug.log"
fi

# Wrap exec in a function so we can redirect its output cleanly
exec_i3() {
    exec i3 -V -d all
}

# Start i3 and log output
logdir="$HOME/.logs"
mkdir -p "$logdir"
"$HOME/dot/bin/cleanup_logs.sh"
i3logfile="$logdir/i3_$(date +"%Y%m%d_%H%M%S").log"
echo "Starting at $(date)" >> "$i3logfile"
echo "PATH: $PATH" >> "$i3logfile"
echo "Checking for i3: $(command -v i3 2>&1)" >> "$i3logfile"

# Try to start i3 and log any errors
if command -v i3 >/dev/null 2>&1; then
  echo "Found i3 at: $(command -v i3)" >> "$i3logfile"
  echo "DISPLAY is: $DISPLAY" >> "$i3logfile"
  exec_i3 >> "$i3logfile" 2>&1
else
  echo "ERROR: i3 not found in PATH" >> "$i3logfile"
  echo "PATH was: $PATH" >> "$i3logfile"
  # Try to show a notification
  notify-send "X Session Failed" "i3 not found in PATH" 2>/dev/null || true
  exit 1
fi
