# Add user-defined fonts
xset +fp /home/paul/.fonts
xset fp rehash

# Disable DPMS turning off the screen
xset dpms force on
xset s off

# Disable bell
xset -b

# Enable zapping (C-A-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp

# Enforce correct locales from the beginning
unset LC_COLLATE
export LC_CTYPE=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=C
export LC_PAPER=en_US.UTF-8
export LC_NAME=en_US.UTF-8
export LC_ADDRESS=en_US.UTF-8
export LC_TELEPHONE=en_US.UTF-8
export LC_MEASUREMENT=en_US.UTF-8
export LC_IDENTIFICATION=en_US.UTF-8

# Use XToolkit in java applications
export AWT_TOOLKIT=XToolkit

# Set background color
xsetroot -solid "#333333"

# Enable core dumps in case something goes wrong
ulimit -c unlimited

# Set up environment variables
source ~/dot/config/env

# Start i3 and log output
logdir="$HOME/.logs"
mkdir -p "$logdir"
$HOME/dot/bin/cleanup_logs.sh
i3logfile="$logdir/i3_$(date +"%Y%m%d_%H%M%S").log"
echo "Starting at $(date)" >> "$i3logfile"
exec /usr/local/bin/i3 -V -d all >> "$i3logfile"

