export DOTFILES=$HOME/.dotfiles
export EDITOR='nvim'

add_to_path() {
    [[ -d "$1" ]] && export PATH="$1:$PATH"
}

# Add the following directories to PATH if they exist:
add_to_path "/usr/local/bin"
add_to_path "/usr/local/sbin"
add_to_path "$DOTFILES/bin"
add_to_path "$DOTFILES/tools"
add_to_path "$HOME/bin"
add_to_path "$HOME/.rvm/bin"
add_to_path "$HOME/.npm-global/bin"
add_to_path "/usr/local/go/bin"
add_to_path "$HOME/go/bin"
add_to_path "$HOME/go"
add_to_path "$HOME/.local/bin"

# Load config files
for config ($DOTFILES/config/zsh/**/*.zsh) source $config

# Set up Node Version Manager.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Alias git to hub; see https://github.com/github/hub
if hash hub 2>/dev/null; then
    eval "$(hub alias -s)"
fi

if [[ -e ~/.localrc ]]; then
    source ~/.localrc
fi

if [[ -e ~/.profile ]]; then
    source ~/.profile
fi

ubuntu_provision_script=$DOTFILES/scripts/provision/ubuntu.sh
if [[ -e $ubuntu_provision_script ]]; then
    source $ubuntu_provision_script
fi

