#!/usr/bin/env bash

cheatsheet_path=$HOME/Dropbox/Pictures/CheatSheets/AppsCheatSheet.png
pid_file=$HOME/.tmp/cheatsheet_pid

print_usage(){
  echo "Usage: ./app_cheatsheet.sh [OPTIONS]"
  echo -en '\n'

  echo "Options:"
  echo "  -k        Kill; hide the cheatsheet"
  echo "  -h        Help; displays usage dialog"
  echo -en '\n'
}

hide=false

while getopts "kh" flag
do
  case "$flag" in
    "k")
      hide=true
      ;;
    "h")
      print_usage
      exit 0
      ;;
    *)
      print_usage
      exit 1
      ;;
  esac
done

if [[ "$hide" = true ]]; then
    if [[ -e $pid_file ]]; then
        feh_pid=$(cat "$pid_file")
        rm "$pid_file"
        kill "$feh_pid"
    fi

    exit 0
fi

mkdir -p "$HOME/.tmp"
feh --scale-down "$cheatsheet_path" &
echo "$!" > "$pid_file"

