#!/usr/bin/env bash

screenshot_dir=$HOME/Pictures/screenshots

mkdir -p $screenshot_dir

error() {
    >&2 echo $1
    exit 1
}

ensure_installed() {
  path=$(which $1)
  if [[ $path == "" ]]; then
      error "$path is not installed..."
  fi
}

filename=$screenshot_dir/$(date +%Y%m%d_%H%M%S).png

ensure_installed scrot
scrot -s $filename

ensure_installed feh
feh $filename

